ABS: false
DG: false
FSGD: false
O2LS: false
PCB: false
TripletSwin: false
adv: 0.0
aiter: 10
arcface: false
batchsize: 32
center: false
centroid: false
circle: false
color_jitter: false
contrast: false
cosface: false
cosine: false
data_dir: /home/jun/ReID_Dataset/duke_background10/dataloader/
droprate: 0.5
erasing_p: 0
fp16: false
gpu_ids:
- 0
ibn: false
ins_gamma: 32
instance: false
lifted: false
linear_num: 1024
lr: 0.01
name: ResNet50_background_erasing10
nclasses: 702
sphere: false
stride: 2
total_epoch: 60
train_all: false
triplet: true
use_NAS: false
use_caswin: false
use_convnext: false
use_dense: false
use_efficient: false
use_hr: false
use_laswin: false
use_laswinv2: false
use_latrans: false
use_latransv2: false
use_lenet: false
use_swin: false
use_swinv2: false
use_vit: false
use_vitraw: false
warm_epoch: 5
weight_decay: 0.0005
