MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/jun/pretrained_models/resnet50-19c8e357.pth'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  NAME: 'SPResNet50_foreground_part_global_mean'
  DEVICE: 'cuda'
  DEVICE_ID: ('0')
  LAST_STRIDE: '1'
  IF_LABELSMOOTH: 'on'
  NECK: 'bnneck'


INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PADDING: 10

DATASETS:
  NAMES: ('dukemtmc')
  ROOT_DIR: '/home/jun/ReID_Dataset'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 80
  BASE_LR: 0.0002
  BIAS_LR_FACTOR: 2
  MOMENTUM: 0.9
  MARGIN: 0.3
  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [20, 60]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 20
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'yes'
  WEIGHT: "/home/jun/reid-strong-baseline/log/SPResNet50_foreground_part_global_mean/SPResNet50_foreground_part_global_mean_model_28920.pt"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "/home/jun/reid-strong-baseline/log/SPResNet50_foreground_part_global_mean"


