#!/bin/bash 

python3 train.py --use_laswin --triplet --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected/ --lr 0.01 --batch 64 --erasing_p 0.5  --warm_epoch 5 --name LASwin_all_trick_cuhk03 --gpu_ids $1
python3 cross_test.py --name LASwin_all_trick_cuhk03 --test duke --gpu_ids $1
python3 cross_test.py --name LASwin_all_trick_cuhk03 --test market --gpu_ids $1
python3 cross_test.py --name LASwin_all_trick_cuhk03 --test cuhk03 --gpu_ids $1