#!/bin/bash


### cross_test for ConvNext
## Market1501
# market-market
python3 cross_test.py --name convnext_all_trick_market --gpu_ids $1 --test market
# market-cuhk03
python3 cross_test.py --name convnext_all_trick_market --gpu_ids $1 --test cuhk03
# market-duke
python3 cross_test.py --name convnext_all_trick_market --gpu_ids $1 --test duke
## cuhk03
# cuhk03-market
python3 cross_test.py --name convnext_all_trick_cuhk03 --gpu_ids $1 --test market
# cuhk03-cuhk03
python3 cross_test.py --name convnext_all_trick_cuhk03 --gpu_ids $1 --test cuhk03
# cuhk03-duke
python3 cross_test.py --name convnext_all_trick_cuhk03 --gpu_ids $1 --test duke
## DukeMTMC
# duke-market
python3 cross_test.py --name convnext_all_trick_duke --gpu_ids $1 --test market
# duke-cuhk03
python3 cross_test.py --name convnext_all_trick_duke --gpu_ids $1 --test cuhk03
# duke-duke
python3 cross_test.py --name convnext_all_trick_duke --gpu_ids $1 --test duke

### cross_test for densenet121
## Market1501
# market-market
python3 cross_test.py --name dense_all_trick_market --gpu_ids $1 --test market
# market-cuhk03
python3 cross_test.py --name dense_all_trick_market --gpu_ids $1 --test cuhk03
# market-duke
python3 cross_test.py --name dense_all_trick_market --gpu_ids $1 --test duke
## cuhk03
# cuhk03-market
python3 cross_test.py --name dense_all_trick_cuhk03 --gpu_ids $1 --test market
# cuhk03-cuhk03
python3 cross_test.py --name dense_all_trick_cuhk03 --gpu_ids $1 --test cuhk03
# cuhk03-duke
python3 cross_test.py --name dense_all_trick_cuhk03 --gpu_ids $1 --test duke
## DukeMTMC
# duke-market
python3 cross_test.py --name dense_all_trick_duke --gpu_ids $1 --test market
# duke-cuhk03
python3 cross_test.py --name dense_all_trick_duke --gpu_ids $1 --test cuhk03
# duke-duke
python3 cross_test.py --name dense_all_trick_duke --gpu_ids $1 --test duke

### cross_test for efficientnet-b4
## Market1501
# market-market
python3 cross_test.py --name efficient_all_trick_market --gpu_ids $1 --test market
# market-cuhk03
python3 cross_test.py --name efficient_all_trick_market --gpu_ids $1 --test cuhk03
# market-duke
python3 cross_test.py --name efficient_all_trick_market --gpu_ids $1 --test duke
## cuhk03
# cuhk03-market
python3 cross_test.py --name efficient_all_trick_cuhk03 --gpu_ids $1 --test market
# cuhk03-cuhk03
python3 cross_test.py --name efficient_all_trick_cuhk03 --gpu_ids $1 --test cuhk03
# cuhk03-duke
python3 cross_test.py --name efficient_all_trick_cuhk03 --gpu_ids $1 --test duke
## DukeMTMC
# duke-market
python3 cross_test.py --name efficient_all_trick_duke --gpu_ids $1 --test market
# duke-cuhk03
python3 cross_test.py --name efficient_all_trick_duke --gpu_ids $1 --test cuhk03
# duke-duke
python3 cross_test.py --name efficient_all_trick_duke --gpu_ids $1 --test duke

### cross_test for hrNet
## Market1501
# market-market
python3 cross_test.py --name hr_all_trick_market --gpu_ids $1 --test market
# market-cuhk03
python3 cross_test.py --name hr_all_trick_market --gpu_ids $1 --test cuhk03
# market-duke
python3 cross_test.py --name hr_all_trick_market --gpu_ids $1 --test duke
## cuhk03
# cuhk03-market
python3 cross_test.py --name hr_all_trick_cuhk03 --gpu_ids $1 --test market
# cuhk03-cuhk03
python3 cross_test.py --name hr_all_trick_cuhk03 --gpu_ids $1 --test cuhk03
# cuhk03-duke
python3 cross_test.py --name hr_all_trick_cuhk03 --gpu_ids $1 --test duke
## DukeMTMC
# duke-market
python3 cross_test.py --name hr_all_trick_duke --gpu_ids $1 --test market
# duke-cuhk03
python3 cross_test.py --name hr_all_trick_duke --gpu_ids $1 --test cuhk03
# duke-duke
python3 cross_test.py --name hr_all_trick_duke --gpu_ids $1 --test duke

### cross_test for NAS
## Market1501
# market-market
python3 cross_test.py --name NAS_all_trick_market --gpu_ids $1 --test market
# market-cuhk03
python3 cross_test.py --name NAS_all_trick_market --gpu_ids $1 --test cuhk03
# market-duke
python3 cross_test.py --name NAS_all_trick_market --gpu_ids $1 --test duke
## cuhk03
# cuhk03-market
python3 cross_test.py --name NAS_all_trick_cuhk03 --gpu_ids $1 --test market
# cuhk03-cuhk03
python3 cross_test.py --name NAS_all_trick_cuhk03 --gpu_ids $1 --test cuhk03
# cuhk03-duke
python3 cross_test.py --name NAS_all_trick_cuhk03 --gpu_ids $1 --test duke
## DukeMTMC
# duke-market
python3 cross_test.py --name NAS_all_trick_duke --gpu_ids $1 --test market
# duke-cuhk03
python3 cross_test.py --name NAS_all_trick_duke --gpu_ids $1 --test cuhk03
# duke-duke
python3 cross_test.py --name NAS_all_trick_duke3 --gpu_ids $1 --test duke

### cross_test for PCB
## Market1501
# market-market
python3 cross_test.py --name PCB_all_trick_market --gpu_ids $1 --test market
# market-cuhk03
python3 cross_test.py --name PCB_all_trick_market --gpu_ids $1 --test cuhk03
# market-duke
python3 cross_test.py --name PCB_all_trick_market --gpu_ids $1 --test duke
## cuhk03
# cuhk03-market
python3 cross_test.py --name PCB_all_trick_cuhk03 --gpu_ids $1 --test market
# cuhk03-cuhk03
python3 cross_test.py --name PCB_all_trick_cuhk03 --gpu_ids $1 --test cuhk03
# cuhk03-duke
python3 cross_test.py --name PCB_all_trick_cuhk03 --gpu_ids $1 --test duke
## DukeMTMC
# duke-market
python3 cross_test.py --name PCB_all_trick_duke --gpu_ids $1 --test market
# duke-cuhk03
python3 cross_test.py --name PCB_all_trick_duke --gpu_ids $1 --test cuhk03
# duke-duke
python3 cross_test.py --name PCB_all_trick_duke --gpu_ids $1 --test duke

### cross_test for resnet
## Market1501
# market-market
python3 cross_test.py --name resnet_all_trick_market --gpu_ids $1 --test market
# market-cuhk03
python3 cross_test.py --name resnet_all_trick_market --gpu_ids $1 --test cuhk03
# market-duke
python3 cross_test.py --name resnet_all_trick_market --gpu_ids $1 --test duke
## cuhk03
# cuhk03-market
python3 cross_test.py --name resnet_all_trick_cuhk03 --gpu_ids $1 --test market
# cuhk03-cuhk03
python3 cross_test.py --name resnet_all_trick_cuhk03 --gpu_ids $1 --test cuhk03
# cuhk03-duke
python3 cross_test.py --name resnet_all_trick_cuhk03 --gpu_ids $1 --test duke
## DukeMTMC
# duke-market
python3 cross_test.py --name resnet_all_trick_duke --gpu_ids $1 --test market
# duke-cuhk03
python3 cross_test.py --name resnet_all_trick_duke --gpu_ids $1 --test cuhk03
# duke-duke
python3 cross_test.py --name resnet_all_trick_duke --gpu_ids $1 --test duke

### cross_test for swin
## Market1501
# market-market
python3 cross_test.py --name swin_all_trick_market --gpu_ids $1 --test market
# market-cuhk03
python3 cross_test.py --name swin_all_trick_market --gpu_ids $1 --test cuhk03
# market-duke
python3 cross_test.py --name swin_all_trick_market --gpu_ids $1 --test duke
## cuhk03
# cuhk03-market
python3 cross_test.py --name swin_all_trick_cuhk03 --gpu_ids $1 --test market
# cuhk03-cuhk03
python3 cross_test.py --name swin_all_trick_cuhk03 --gpu_ids $1 --test cuhk03
# cuhk03-duke
python3 cross_test.py --name swin_all_trick_cuhk03 --gpu_ids $1 --test duke
## DukeMTMC
# duke-market
python3 cross_test.py --name swin_all_trick_duke --gpu_ids $1 --test market
# duke-cuhk03
python3 cross_test.py --name swin_all_trick_duke --gpu_ids $1 --test cuhk03
# duke-duke
python3 cross_test.py --name swin_all_trick_duke --gpu_ids $1 --test duke

### cross_test for vit
## Market1501
# market-market
python3 cross_test.py --name vit_all_trick_market --gpu_ids $1 --test market
# market-cuhk03
python3 cross_test.py --name vit_all_trick_market --gpu_ids $1 --test cuhk03
# market-duke
python3 cross_test.py --name vit_all_trick_market --gpu_ids $1 --test duke
## cuhk03
# cuhk03-market
python3 cross_test.py --name vit_all_trick_cuhk03 --gpu_ids $1 --test market
# cuhk03-cuhk03
python3 cross_test.py --name vit_all_trick_cuhk03 --gpu_ids $1 --test cuhk03
# cuhk03-duke
python3 cross_test.py --name vit_all_trick_cuhk03 --gpu_ids $1 --test duke
## DukeMTMC
# duke-market
python3 cross_test.py --name vit_all_trick_duke --gpu_ids $1 --test market
# duke-cuhk03
python3 cross_test.py --name vit_all_trick_duke --gpu_ids $1 --test cuhk03
# duke-duke
python3 cross_test.py --name vit_all_trick_duke --gpu_ids $1 --test duke