#!/bin/bash


### Train for ConvNext
## Market1501
python3 train.py --gpu_ids $1 --use_latran --circle --data_dir /home/jun/ReID_Dataset/market/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name latrancircle_all_trick_market; python3 test.py --name  latrancircle_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --use_latran --circle --data_dir /home/jun/ReID_Dataset/duke/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name latrancircle_all_trick_duke; python3 test.py --name  latrancircle_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --use_latran --circle --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name  latrancircle_all_trick_cuhk03; python3 test.py --name --name  latrancircle_all_trick_cuhk03 --gpu_ids $1
