#!/bin/bash


### Train for ConvNext
## Market1501
python3 train.py --gpu_ids $1 --use_convnext --data_dir /home/jun/ReID_Dataset/market1501/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name convnext_all_trick_market; python3 test.py --name convnext_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --use_convnext --data_dir /home/jun/ReID_Dataset/dukemtmcreid/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name convnext_all_trick_duke; python3 test.py --name convnext_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --use_convnext --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name convnext_all_trick_cuhk03; python3 test.py --name convnext_all_trick_cuhk03 --gpu_ids $1
#!/bin/bash


### Train for densenet121
## Market1501
python3 train.py --gpu_ids $1 --use_dense --data_dir /home/jun/ReID_Dataset/market1501/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name dense_all_trick_market; python3 test.py --name dense_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --use_dense --data_dir /home/jun/ReID_Dataset/dukemtmcreid/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name dense_all_trick_duke; python3 test.py --name dense_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --use_dense --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name dense_all_trick_cuhk03; python3 test.py --name dense_all_trick_cuhk03 --gpu_ids $1
#!/bin/bash


### Train for efficientnet-b4
## Market1501
python3 train.py --gpu_ids $1 --use_efficient --data_dir /home/jun/ReID_Dataset/market1501/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name efficient_all_trick_market; python3 test.py --name efficient_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --use_efficient --data_dir /home/jun/ReID_Dataset/dukemtmcreid/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name efficient_all_trick_duke; python3 test.py --name efficient_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --use_efficient --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name efficient_all_trick_cuhk03; python3 test.py --name efficient_all_trick_cuhk03 --gpu_ids $1
#!/bin/bash


### Train for hrNet
## Market1501
python3 train.py --gpu_ids $1 --use_hr --data_dir /home/jun/ReID_Dataset/market1501/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name hr_all_trick_market; python3 test.py --name hr_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --use_hr --data_dir /home/jun/ReID_Dataset/dukemtmcreid/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name hr_all_trick_duke; python3 test.py --name hr_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --use_hr --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name hr_all_trick_cuhk03; python3 test.py --name hr_all_trick_cuhk03 --gpu_ids $1
#!/bin/bash


### Train for NAS
## Market1501
python3 train.py --gpu_ids $1 --use_NAS --data_dir /home/jun/ReID_Dataset/market1501/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name NAS_all_trick_market; python3 test.py --name NAS_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --use_NAS --data_dir /home/jun/ReID_Dataset/dukemtmcreid/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name NAS_all_trick_duke; python3 test.py --name NAS_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --use_NAS --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name NAS_all_trick_cuhk03; python3 test.py --name NAS_all_trick_cuhk03 --gpu_ids $1
#!/bin/bash

### Train for PCB
## Market1501
python3 train.py --gpu_ids $1 --PCB --data_dir /home/jun/ReID_Dataset/market1501/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name PCB_all_trick_market; python3 test.py --name PCB_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --PCB --data_dir /home/jun/ReID_Dataset/dukemtmcreid/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name PCB_all_trick_duke; python3 test.py --name PCB_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --PCB --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name PCB_all_trick_cuhk03; python3 test.py --name PCB_all_trick_cuhk03 --gpu_ids $1
#!/bin/bash


### Train for resnet
## Market1501
python3 train.py --gpu_ids $1 --data_dir /home/jun/ReID_Dataset/market1501/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name resnet_all_trick_market; python3 test.py --name resnet_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --data_dir /home/jun/ReID_Dataset/dukemtmcreid/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name resnet_all_trick_duke; python3 test.py --name resnet_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name resnet_all_trick_cuhk03; python3 test.py --name resnet_all_trick_cuhk03 --gpu_ids $1
#!/bin/bash

### Train for swin
## Market1501
python3 train.py --gpu_ids $1 --use_swin --data_dir /home/jun/ReID_Dataset/market1501/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name swin_all_trick_market; python3 test.py --name swin_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --use_swin --data_dir /home/jun/ReID_Dataset/dukemtmcreid/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name swin_all_trick_duke; python3 test.py --name swin_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --use_swin --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name swin_all_trick_cuhk03; python3 test.py --name swin_all_trick_cuhk03 --gpu_ids $1
#!/bin/bash

### Train for vit
## Market1501
python3 train.py --gpu_ids $1 --use_vit --data_dir /home/jun/ReID_Dataset/market1501/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name vit_all_trick_market; python3 test.py --name vit_all_trick_market --gpu_ids $1
## DukeMTMC
python3 train.py --gpu_ids $1 --use_vit --data_dir /home/jun/ReID_Dataset/dukemtmcreid/dataloader --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name vit_all_trick_duke; python3 test.py --name vit_all_trick_duke --gpu_ids $1
## Cuhk03
python3 train.py --gpu_ids $1 --use_vit --data_dir /home/jun/ReID_Dataset/cuhk03/dataloader_new_detected --lr 0.01 --batch 16 --erasing_p 0.5  --warm_epoch 5 --name vit_all_trick_cuhk03; python3 test.py --name vit_all_trick_cuhk03 --gpu_ids $1
