#!/bin/bash 

python3 train.py --use_vit --triplet --data_dir /home/jun/ReID_Dataset/duke/dataloader/ --lr 0.01 --batch 64 --erasing_p 0.5  --warm_epoch 5 --name ViT_all_trick_duke --gpu_ids $1
python3 cross_test.py --name ViT_all_trick_duke --test duke --gpu_ids $1
python3 cross_test.py --name ViT_all_trick_duke --test market --gpu_ids $1
python3 cross_test.py --name ViT_all_trick_duke --test cuhk03 --gpu_ids $1
