#!/bin/sh
CUDA_VISIBLE_DEVICES=0 \

python3 source_pretrain.py -dt market1501 --height 224 --width 224 -ds dukemtmc -a Swin --seed 0 --margin 0.0 \
	--num-instances 4 -b 32 -j 4 --warmup-step 10 --lr 0.00035 --milestones 40 70 --iters 400 --epochs 100 \
	--eval-step 10 --logs-dir logs/dukemtmcTOmarket1501/Swin_0.00035

#DBSCAN Baseline

python3 sbs_traindbscan.py --height 224 --width 224  --lr 0.00035  -st dukemtmc -tt market1501 -a Swin \
    --num-instances 4 --iters 400 -b 32 --epochs 200        --eval-step 6 --dropout 0 --n-jobs 16 --choice_c 0 \
	--init-1 logs/dukemtmcTOmarket1501/Swin/model_best.pth.tar \
   	--logs-dir logs/dbscan-dukemtmcTOmarket1501/Swin_0.00035

python3 source_pretrain.py -ds market1501 --height 224 --width 224 -dt dukemtmc -a Swin --seed 0 --margin 0.0 \
	--num-instances 4 -b 32 -j 4 --warmup-step 10 --lr 0.00035 --milestones 40 70 --iters 400 --epochs 100 \
	--eval-step 10 --logs-dir logs/market1501TOdukemtmc/Swin_0.00035


python3 sbs_traindbscan_unc.py --height 224 --width 224  --lr 0.001  --schedule_step 10 -st dukemtmc -tt market1501 -a Swin\
	--num-instances 4 --iters 400 -b 32 --epochs 200 \
	--eval-step 10 --dropout 0 --n-jobs 16 --choice_c 0 \
	--init-1 logs/dukemtmcTOmarket1501/Swin/model_best.pth.tar \
	--logs-dir logs/dbscan-dukemtmcTOmarket1501/Swin_uncertainly_0.00035
